### PR TITLE
Crunchbase investors

### PR DESCRIPTION
**Pull request by josselinlbe**

### CODE REVIEW

**Comment by seelixe** [comment]
Hello @TASnomad,
Yes it's ok for x investors. 

Also, relatedCompanies is not good since the "About" page arrived.

**Comment by TASnomad** [comment]
From your tests, we didn't find the same CSS selector as yours.
I'm not sure about this situation, we only can make your tests working with `funding_last_round_investors_link` selector.

**Comment by seelixe** [comment]
I didn't find `funding_last_round_investors_link`. I only have this one `funding_lead_investor_link` 🤕

**Comment by Spygn** [comment]
Problem with LinkedIn is that some accounts have different selectors :/
fundinglastround

**Comment by seelixe** [comment]
Today i have 2 data-control `funding_lead_investor_link` and 1 `funding_last_round_investors_link`. :/

**Comment by TASnomad** [comment]
Hello @josselinlbe, any updates for this PR?

**Comment by josselinlbe** [comment]
It's ok, thanks !

**Pull request closed without merging**
